// <auto-generated />
namespace QuanLyPhongTro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModifyNgayKetThucToHopDong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyNgayKetThucToHopDong));
        
        string IMigrationMetadata.Id
        {
            get { return "202306021504020_ModifyNgayKetThucToHopDong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
