#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.DBLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyPhongTro.QLPhongTroCodeFristModel")]
	public partial class QuanLyPhongTroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuTroe(ChuTroe instance);
    partial void UpdateChuTroe(ChuTroe instance);
    partial void DeleteChuTroe(ChuTroe instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertNguoiDungChuTroe(NguoiDungChuTroe instance);
    partial void UpdateNguoiDungChuTroe(NguoiDungChuTroe instance);
    partial void DeleteNguoiDungChuTroe(NguoiDungChuTroe instance);
    partial void InsertNguoiDungNguoiThue(NguoiDungNguoiThue instance);
    partial void UpdateNguoiDungNguoiThue(NguoiDungNguoiThue instance);
    partial void DeleteNguoiDungNguoiThue(NguoiDungNguoiThue instance);
    partial void InsertNguoiThue(NguoiThue instance);
    partial void UpdateNguoiThue(NguoiThue instance);
    partial void DeleteNguoiThue(NguoiThue instance);
    partial void InsertPhongTroe(PhongTroe instance);
    partial void UpdatePhongTroe(PhongTroe instance);
    partial void DeletePhongTroe(PhongTroe instance);
    #endregion
		
		public QuanLyPhongTroDataContext() : 
				base(global::QuanLyPhongTro.Properties.Settings.Default.QuanLyPhongTro_QLPhongTroCodeFristModelConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongTroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuTroe> ChuTroes
		{
			get
			{
				return this.GetTable<ChuTroe>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDungChuTroe> NguoiDungChuTroes
		{
			get
			{
				return this.GetTable<NguoiDungChuTroe>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDungNguoiThue> NguoiDungNguoiThues
		{
			get
			{
				return this.GetTable<NguoiDungNguoiThue>();
			}
		}
		
		public System.Data.Linq.Table<NguoiThue> NguoiThues
		{
			get
			{
				return this.GetTable<NguoiThue>();
			}
		}
		
		public System.Data.Linq.Table<PhongTroe> PhongTroes
		{
			get
			{
				return this.GetTable<PhongTroe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuTroes")]
	public partial class ChuTroe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSo;
		
		private string _Ten;
		
		private string _CCCD;
		
		private System.DateTime _NgaySinh;
		
		private string _QueQuan;
		
		private string _SDT;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntitySet<NguoiDungChuTroe> _NguoiDungChuTroes;
		
		private EntitySet<PhongTroe> _PhongTroes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public ChuTroe()
		{
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._NguoiDungChuTroes = new EntitySet<NguoiDungChuTroe>(new Action<NguoiDungChuTroe>(this.attach_NguoiDungChuTroes), new Action<NguoiDungChuTroe>(this.detach_NguoiDungChuTroes));
			this._PhongTroes = new EntitySet<PhongTroe>(new Action<PhongTroe>(this.attach_PhongTroes), new Action<PhongTroe>(this.detach_PhongTroes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(MAX)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(MAX)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(MAX)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(MAX)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuTroe_HopDong", Storage="_HopDongs", ThisKey="MaSo", OtherKey="ChuTro_MaSo")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuTroe_NguoiDungChuTroe", Storage="_NguoiDungChuTroes", ThisKey="MaSo", OtherKey="ChuTro_MaSo")]
		public EntitySet<NguoiDungChuTroe> NguoiDungChuTroes
		{
			get
			{
				return this._NguoiDungChuTroes;
			}
			set
			{
				this._NguoiDungChuTroes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuTroe_PhongTroe", Storage="_PhongTroes", ThisKey="MaSo", OtherKey="ChuTro_MaSo")]
		public EntitySet<PhongTroe> PhongTroes
		{
			get
			{
				return this._PhongTroes;
			}
			set
			{
				this._PhongTroes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.ChuTroe = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.ChuTroe = null;
		}
		
		private void attach_NguoiDungChuTroes(NguoiDungChuTroe entity)
		{
			this.SendPropertyChanging();
			entity.ChuTroe = this;
		}
		
		private void detach_NguoiDungChuTroes(NguoiDungChuTroe entity)
		{
			this.SendPropertyChanging();
			entity.ChuTroe = null;
		}
		
		private void attach_PhongTroes(PhongTroe entity)
		{
			this.SendPropertyChanging();
			entity.ChuTroe = this;
		}
		
		private void detach_PhongTroes(PhongTroe entity)
		{
			this.SendPropertyChanging();
			entity.ChuTroe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDons")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSo;
		
		private int _SoDienTieuThu;
		
		private int _SoNuocTieuThu;
		
		private System.DateTime _NgayDau;
		
		private System.DateTime _NgayCuoi;
		
		private bool _DaThanhToan;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private string _PhongTro_MaSo;
		
		private EntityRef<PhongTroe> _PhongTroe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnSoDienTieuThuChanging(int value);
    partial void OnSoDienTieuThuChanged();
    partial void OnSoNuocTieuThuChanging(int value);
    partial void OnSoNuocTieuThuChanged();
    partial void OnNgayDauChanging(System.DateTime value);
    partial void OnNgayDauChanged();
    partial void OnNgayCuoiChanging(System.DateTime value);
    partial void OnNgayCuoiChanged();
    partial void OnDaThanhToanChanging(bool value);
    partial void OnDaThanhToanChanged();
    partial void OnNgayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhToanChanged();
    partial void OnPhongTro_MaSoChanging(string value);
    partial void OnPhongTro_MaSoChanged();
    #endregion
		
		public HoaDon()
		{
			this._PhongTroe = default(EntityRef<PhongTroe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienTieuThu", DbType="Int NOT NULL")]
		public int SoDienTieuThu
		{
			get
			{
				return this._SoDienTieuThu;
			}
			set
			{
				if ((this._SoDienTieuThu != value))
				{
					this.OnSoDienTieuThuChanging(value);
					this.SendPropertyChanging();
					this._SoDienTieuThu = value;
					this.SendPropertyChanged("SoDienTieuThu");
					this.OnSoDienTieuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNuocTieuThu", DbType="Int NOT NULL")]
		public int SoNuocTieuThu
		{
			get
			{
				return this._SoNuocTieuThu;
			}
			set
			{
				if ((this._SoNuocTieuThu != value))
				{
					this.OnSoNuocTieuThuChanging(value);
					this.SendPropertyChanging();
					this._SoNuocTieuThu = value;
					this.SendPropertyChanged("SoNuocTieuThu");
					this.OnSoNuocTieuThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDau", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDau
		{
			get
			{
				return this._NgayDau;
			}
			set
			{
				if ((this._NgayDau != value))
				{
					this.OnNgayDauChanging(value);
					this.SendPropertyChanging();
					this._NgayDau = value;
					this.SendPropertyChanged("NgayDau");
					this.OnNgayDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCuoi", DbType="DateTime NOT NULL")]
		public System.DateTime NgayCuoi
		{
			get
			{
				return this._NgayCuoi;
			}
			set
			{
				if ((this._NgayCuoi != value))
				{
					this.OnNgayCuoiChanging(value);
					this.SendPropertyChanging();
					this._NgayCuoi = value;
					this.SendPropertyChanged("NgayCuoi");
					this.OnNgayCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaThanhToan", DbType="Bit NOT NULL")]
		public bool DaThanhToan
		{
			get
			{
				return this._DaThanhToan;
			}
			set
			{
				if ((this._DaThanhToan != value))
				{
					this.OnDaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._DaThanhToan = value;
					this.SendPropertyChanged("DaThanhToan");
					this.OnDaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongTro_MaSo", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PhongTro_MaSo
		{
			get
			{
				return this._PhongTro_MaSo;
			}
			set
			{
				if ((this._PhongTro_MaSo != value))
				{
					if (this._PhongTroe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongTro_MaSoChanging(value);
					this.SendPropertyChanging();
					this._PhongTro_MaSo = value;
					this.SendPropertyChanged("PhongTro_MaSo");
					this.OnPhongTro_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongTroe_HoaDon", Storage="_PhongTroe", ThisKey="PhongTro_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public PhongTroe PhongTroe
		{
			get
			{
				return this._PhongTroe.Entity;
			}
			set
			{
				PhongTroe previousValue = this._PhongTroe.Entity;
				if (((previousValue != value) 
							|| (this._PhongTroe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongTroe.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._PhongTroe.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._PhongTro_MaSo = value.MaSo;
					}
					else
					{
						this._PhongTro_MaSo = default(string);
					}
					this.SendPropertyChanged("PhongTroe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDongs")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSo;
		
		private System.DateTime _NgayTao;
		
		private double _TienCoc;
		
		private int _ThoiHanCoc;
		
		private bool _DaLayTienCoc;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private string _ChuTro_MaSo;
		
		private string _NguoiThue_MaSo;
		
		private string _PhongTro_MaSo;
		
		private EntityRef<ChuTroe> _ChuTroe;
		
		private EntityRef<NguoiThue> _NguoiThue;
		
		private EntityRef<PhongTroe> _PhongTroe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnTienCocChanging(double value);
    partial void OnTienCocChanged();
    partial void OnThoiHanCocChanging(int value);
    partial void OnThoiHanCocChanged();
    partial void OnDaLayTienCocChanging(bool value);
    partial void OnDaLayTienCocChanged();
    partial void OnNgayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucChanged();
    partial void OnChuTro_MaSoChanging(string value);
    partial void OnChuTro_MaSoChanged();
    partial void OnNguoiThue_MaSoChanging(string value);
    partial void OnNguoiThue_MaSoChanged();
    partial void OnPhongTro_MaSoChanging(string value);
    partial void OnPhongTro_MaSoChanged();
    #endregion
		
		public HopDong()
		{
			this._ChuTroe = default(EntityRef<ChuTroe>);
			this._NguoiThue = default(EntityRef<NguoiThue>);
			this._PhongTroe = default(EntityRef<PhongTroe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienCoc", DbType="Float NOT NULL")]
		public double TienCoc
		{
			get
			{
				return this._TienCoc;
			}
			set
			{
				if ((this._TienCoc != value))
				{
					this.OnTienCocChanging(value);
					this.SendPropertyChanging();
					this._TienCoc = value;
					this.SendPropertyChanged("TienCoc");
					this.OnTienCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHanCoc", DbType="Int NOT NULL")]
		public int ThoiHanCoc
		{
			get
			{
				return this._ThoiHanCoc;
			}
			set
			{
				if ((this._ThoiHanCoc != value))
				{
					this.OnThoiHanCocChanging(value);
					this.SendPropertyChanging();
					this._ThoiHanCoc = value;
					this.SendPropertyChanged("ThoiHanCoc");
					this.OnThoiHanCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaLayTienCoc", DbType="Bit NOT NULL")]
		public bool DaLayTienCoc
		{
			get
			{
				return this._DaLayTienCoc;
			}
			set
			{
				if ((this._DaLayTienCoc != value))
				{
					this.OnDaLayTienCocChanging(value);
					this.SendPropertyChanging();
					this._DaLayTienCoc = value;
					this.SendPropertyChanged("DaLayTienCoc");
					this.OnDaLayTienCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuTro_MaSo", DbType="NVarChar(128)")]
		public string ChuTro_MaSo
		{
			get
			{
				return this._ChuTro_MaSo;
			}
			set
			{
				if ((this._ChuTro_MaSo != value))
				{
					if (this._ChuTroe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChuTro_MaSoChanging(value);
					this.SendPropertyChanging();
					this._ChuTro_MaSo = value;
					this.SendPropertyChanged("ChuTro_MaSo");
					this.OnChuTro_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThue_MaSo", DbType="NVarChar(128)")]
		public string NguoiThue_MaSo
		{
			get
			{
				return this._NguoiThue_MaSo;
			}
			set
			{
				if ((this._NguoiThue_MaSo != value))
				{
					if (this._NguoiThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiThue_MaSoChanging(value);
					this.SendPropertyChanging();
					this._NguoiThue_MaSo = value;
					this.SendPropertyChanged("NguoiThue_MaSo");
					this.OnNguoiThue_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongTro_MaSo", DbType="NVarChar(128)")]
		public string PhongTro_MaSo
		{
			get
			{
				return this._PhongTro_MaSo;
			}
			set
			{
				if ((this._PhongTro_MaSo != value))
				{
					if (this._PhongTroe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongTro_MaSoChanging(value);
					this.SendPropertyChanging();
					this._PhongTro_MaSo = value;
					this.SendPropertyChanged("PhongTro_MaSo");
					this.OnPhongTro_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuTroe_HopDong", Storage="_ChuTroe", ThisKey="ChuTro_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public ChuTroe ChuTroe
		{
			get
			{
				return this._ChuTroe.Entity;
			}
			set
			{
				ChuTroe previousValue = this._ChuTroe.Entity;
				if (((previousValue != value) 
							|| (this._ChuTroe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuTroe.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._ChuTroe.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._ChuTro_MaSo = value.MaSo;
					}
					else
					{
						this._ChuTro_MaSo = default(string);
					}
					this.SendPropertyChanged("ChuTroe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiThue_HopDong", Storage="_NguoiThue", ThisKey="NguoiThue_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public NguoiThue NguoiThue
		{
			get
			{
				return this._NguoiThue.Entity;
			}
			set
			{
				NguoiThue previousValue = this._NguoiThue.Entity;
				if (((previousValue != value) 
							|| (this._NguoiThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiThue.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._NguoiThue.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._NguoiThue_MaSo = value.MaSo;
					}
					else
					{
						this._NguoiThue_MaSo = default(string);
					}
					this.SendPropertyChanged("NguoiThue");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongTroe_HopDong", Storage="_PhongTroe", ThisKey="PhongTro_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public PhongTroe PhongTroe
		{
			get
			{
				return this._PhongTroe.Entity;
			}
			set
			{
				PhongTroe previousValue = this._PhongTroe.Entity;
				if (((previousValue != value) 
							|| (this._PhongTroe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongTroe.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._PhongTroe.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._PhongTro_MaSo = value.MaSo;
					}
					else
					{
						this._PhongTro_MaSo = default(string);
					}
					this.SendPropertyChanged("PhongTroe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDungChuTroes")]
	public partial class NguoiDungChuTroe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _ChuTro_MaSo;
		
		private EntityRef<ChuTroe> _ChuTroe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnChuTro_MaSoChanging(string value);
    partial void OnChuTro_MaSoChanged();
    #endregion
		
		public NguoiDungChuTroe()
		{
			this._ChuTroe = default(EntityRef<ChuTroe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(MAX)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuTro_MaSo", DbType="NVarChar(128)")]
		public string ChuTro_MaSo
		{
			get
			{
				return this._ChuTro_MaSo;
			}
			set
			{
				if ((this._ChuTro_MaSo != value))
				{
					if (this._ChuTroe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChuTro_MaSoChanging(value);
					this.SendPropertyChanging();
					this._ChuTro_MaSo = value;
					this.SendPropertyChanged("ChuTro_MaSo");
					this.OnChuTro_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuTroe_NguoiDungChuTroe", Storage="_ChuTroe", ThisKey="ChuTro_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public ChuTroe ChuTroe
		{
			get
			{
				return this._ChuTroe.Entity;
			}
			set
			{
				ChuTroe previousValue = this._ChuTroe.Entity;
				if (((previousValue != value) 
							|| (this._ChuTroe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuTroe.Entity = null;
						previousValue.NguoiDungChuTroes.Remove(this);
					}
					this._ChuTroe.Entity = value;
					if ((value != null))
					{
						value.NguoiDungChuTroes.Add(this);
						this._ChuTro_MaSo = value.MaSo;
					}
					else
					{
						this._ChuTro_MaSo = default(string);
					}
					this.SendPropertyChanged("ChuTroe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDungNguoiThues")]
	public partial class NguoiDungNguoiThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _NguoiThue_MaSo;
		
		private EntityRef<NguoiThue> _NguoiThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnNguoiThue_MaSoChanging(string value);
    partial void OnNguoiThue_MaSoChanged();
    #endregion
		
		public NguoiDungNguoiThue()
		{
			this._NguoiThue = default(EntityRef<NguoiThue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(MAX)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThue_MaSo", DbType="NVarChar(128)")]
		public string NguoiThue_MaSo
		{
			get
			{
				return this._NguoiThue_MaSo;
			}
			set
			{
				if ((this._NguoiThue_MaSo != value))
				{
					if (this._NguoiThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiThue_MaSoChanging(value);
					this.SendPropertyChanging();
					this._NguoiThue_MaSo = value;
					this.SendPropertyChanged("NguoiThue_MaSo");
					this.OnNguoiThue_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiThue_NguoiDungNguoiThue", Storage="_NguoiThue", ThisKey="NguoiThue_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public NguoiThue NguoiThue
		{
			get
			{
				return this._NguoiThue.Entity;
			}
			set
			{
				NguoiThue previousValue = this._NguoiThue.Entity;
				if (((previousValue != value) 
							|| (this._NguoiThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiThue.Entity = null;
						previousValue.NguoiDungNguoiThues.Remove(this);
					}
					this._NguoiThue.Entity = value;
					if ((value != null))
					{
						value.NguoiDungNguoiThues.Add(this);
						this._NguoiThue_MaSo = value.MaSo;
					}
					else
					{
						this._NguoiThue_MaSo = default(string);
					}
					this.SendPropertyChanged("NguoiThue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiThues")]
	public partial class NguoiThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSo;
		
		private string _Ten;
		
		private string _CCCD;
		
		private System.DateTime _NgaySinh;
		
		private string _QueQuan;
		
		private string _SDT;
		
		private string _PhongTro_MaSo;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntitySet<NguoiDungNguoiThue> _NguoiDungNguoiThues;
		
		private EntityRef<PhongTroe> _PhongTroe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnPhongTro_MaSoChanging(string value);
    partial void OnPhongTro_MaSoChanged();
    #endregion
		
		public NguoiThue()
		{
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._NguoiDungNguoiThues = new EntitySet<NguoiDungNguoiThue>(new Action<NguoiDungNguoiThue>(this.attach_NguoiDungNguoiThues), new Action<NguoiDungNguoiThue>(this.detach_NguoiDungNguoiThues));
			this._PhongTroe = default(EntityRef<PhongTroe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(MAX)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(MAX)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(MAX)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(MAX)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongTro_MaSo", DbType="NVarChar(128)")]
		public string PhongTro_MaSo
		{
			get
			{
				return this._PhongTro_MaSo;
			}
			set
			{
				if ((this._PhongTro_MaSo != value))
				{
					if (this._PhongTroe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongTro_MaSoChanging(value);
					this.SendPropertyChanging();
					this._PhongTro_MaSo = value;
					this.SendPropertyChanged("PhongTro_MaSo");
					this.OnPhongTro_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiThue_HopDong", Storage="_HopDongs", ThisKey="MaSo", OtherKey="NguoiThue_MaSo")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiThue_NguoiDungNguoiThue", Storage="_NguoiDungNguoiThues", ThisKey="MaSo", OtherKey="NguoiThue_MaSo")]
		public EntitySet<NguoiDungNguoiThue> NguoiDungNguoiThues
		{
			get
			{
				return this._NguoiDungNguoiThues;
			}
			set
			{
				this._NguoiDungNguoiThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongTroe_NguoiThue", Storage="_PhongTroe", ThisKey="PhongTro_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public PhongTroe PhongTroe
		{
			get
			{
				return this._PhongTroe.Entity;
			}
			set
			{
				PhongTroe previousValue = this._PhongTroe.Entity;
				if (((previousValue != value) 
							|| (this._PhongTroe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongTroe.Entity = null;
						previousValue.NguoiThues.Remove(this);
					}
					this._PhongTroe.Entity = value;
					if ((value != null))
					{
						value.NguoiThues.Add(this);
						this._PhongTro_MaSo = value.MaSo;
					}
					else
					{
						this._PhongTro_MaSo = default(string);
					}
					this.SendPropertyChanged("PhongTroe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.NguoiThue = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.NguoiThue = null;
		}
		
		private void attach_NguoiDungNguoiThues(NguoiDungNguoiThue entity)
		{
			this.SendPropertyChanging();
			entity.NguoiThue = this;
		}
		
		private void detach_NguoiDungNguoiThues(NguoiDungNguoiThue entity)
		{
			this.SendPropertyChanging();
			entity.NguoiThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongTroes")]
	public partial class PhongTroe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSo;
		
		private double _DienTich;
		
		private string _DiaChi;
		
		private int _SoNguoiToiDa;
		
		private bool _CoGac;
		
		private bool _ChoNuoiThuCung;
		
		private double _TienThue;
		
		private double _TienDien;
		
		private double _TienNuoc;
		
		private double _TienRac;
		
		private string _ChuTro_MaSo;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntitySet<NguoiThue> _NguoiThues;
		
		private EntityRef<ChuTroe> _ChuTroe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnDienTichChanging(double value);
    partial void OnDienTichChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoNguoiToiDaChanging(int value);
    partial void OnSoNguoiToiDaChanged();
    partial void OnCoGacChanging(bool value);
    partial void OnCoGacChanged();
    partial void OnChoNuoiThuCungChanging(bool value);
    partial void OnChoNuoiThuCungChanged();
    partial void OnTienThueChanging(double value);
    partial void OnTienThueChanged();
    partial void OnTienDienChanging(double value);
    partial void OnTienDienChanged();
    partial void OnTienNuocChanging(double value);
    partial void OnTienNuocChanged();
    partial void OnTienRacChanging(double value);
    partial void OnTienRacChanged();
    partial void OnChuTro_MaSoChanging(string value);
    partial void OnChuTro_MaSoChanged();
    #endregion
		
		public PhongTroe()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._NguoiThues = new EntitySet<NguoiThue>(new Action<NguoiThue>(this.attach_NguoiThues), new Action<NguoiThue>(this.detach_NguoiThues));
			this._ChuTroe = default(EntityRef<ChuTroe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="Float NOT NULL")]
		public double DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNguoiToiDa", DbType="Int NOT NULL")]
		public int SoNguoiToiDa
		{
			get
			{
				return this._SoNguoiToiDa;
			}
			set
			{
				if ((this._SoNguoiToiDa != value))
				{
					this.OnSoNguoiToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoNguoiToiDa = value;
					this.SendPropertyChanged("SoNguoiToiDa");
					this.OnSoNguoiToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoGac", DbType="Bit NOT NULL")]
		public bool CoGac
		{
			get
			{
				return this._CoGac;
			}
			set
			{
				if ((this._CoGac != value))
				{
					this.OnCoGacChanging(value);
					this.SendPropertyChanging();
					this._CoGac = value;
					this.SendPropertyChanged("CoGac");
					this.OnCoGacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoNuoiThuCung", DbType="Bit NOT NULL")]
		public bool ChoNuoiThuCung
		{
			get
			{
				return this._ChoNuoiThuCung;
			}
			set
			{
				if ((this._ChoNuoiThuCung != value))
				{
					this.OnChoNuoiThuCungChanging(value);
					this.SendPropertyChanging();
					this._ChoNuoiThuCung = value;
					this.SendPropertyChanged("ChoNuoiThuCung");
					this.OnChoNuoiThuCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThue", DbType="Float NOT NULL")]
		public double TienThue
		{
			get
			{
				return this._TienThue;
			}
			set
			{
				if ((this._TienThue != value))
				{
					this.OnTienThueChanging(value);
					this.SendPropertyChanging();
					this._TienThue = value;
					this.SendPropertyChanged("TienThue");
					this.OnTienThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDien", DbType="Float NOT NULL")]
		public double TienDien
		{
			get
			{
				return this._TienDien;
			}
			set
			{
				if ((this._TienDien != value))
				{
					this.OnTienDienChanging(value);
					this.SendPropertyChanging();
					this._TienDien = value;
					this.SendPropertyChanged("TienDien");
					this.OnTienDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienNuoc", DbType="Float NOT NULL")]
		public double TienNuoc
		{
			get
			{
				return this._TienNuoc;
			}
			set
			{
				if ((this._TienNuoc != value))
				{
					this.OnTienNuocChanging(value);
					this.SendPropertyChanging();
					this._TienNuoc = value;
					this.SendPropertyChanged("TienNuoc");
					this.OnTienNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienRac", DbType="Float NOT NULL")]
		public double TienRac
		{
			get
			{
				return this._TienRac;
			}
			set
			{
				if ((this._TienRac != value))
				{
					this.OnTienRacChanging(value);
					this.SendPropertyChanging();
					this._TienRac = value;
					this.SendPropertyChanged("TienRac");
					this.OnTienRacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuTro_MaSo", DbType="NVarChar(128)")]
		public string ChuTro_MaSo
		{
			get
			{
				return this._ChuTro_MaSo;
			}
			set
			{
				if ((this._ChuTro_MaSo != value))
				{
					if (this._ChuTroe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChuTro_MaSoChanging(value);
					this.SendPropertyChanging();
					this._ChuTro_MaSo = value;
					this.SendPropertyChanged("ChuTro_MaSo");
					this.OnChuTro_MaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongTroe_HoaDon", Storage="_HoaDons", ThisKey="MaSo", OtherKey="PhongTro_MaSo")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongTroe_HopDong", Storage="_HopDongs", ThisKey="MaSo", OtherKey="PhongTro_MaSo")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongTroe_NguoiThue", Storage="_NguoiThues", ThisKey="MaSo", OtherKey="PhongTro_MaSo")]
		public EntitySet<NguoiThue> NguoiThues
		{
			get
			{
				return this._NguoiThues;
			}
			set
			{
				this._NguoiThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuTroe_PhongTroe", Storage="_ChuTroe", ThisKey="ChuTro_MaSo", OtherKey="MaSo", IsForeignKey=true)]
		public ChuTroe ChuTroe
		{
			get
			{
				return this._ChuTroe.Entity;
			}
			set
			{
				ChuTroe previousValue = this._ChuTroe.Entity;
				if (((previousValue != value) 
							|| (this._ChuTroe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuTroe.Entity = null;
						previousValue.PhongTroes.Remove(this);
					}
					this._ChuTroe.Entity = value;
					if ((value != null))
					{
						value.PhongTroes.Add(this);
						this._ChuTro_MaSo = value.MaSo;
					}
					else
					{
						this._ChuTro_MaSo = default(string);
					}
					this.SendPropertyChanged("ChuTroe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhongTroe = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhongTroe = null;
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.PhongTroe = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.PhongTroe = null;
		}
		
		private void attach_NguoiThues(NguoiThue entity)
		{
			this.SendPropertyChanging();
			entity.PhongTroe = this;
		}
		
		private void detach_NguoiThues(NguoiThue entity)
		{
			this.SendPropertyChanging();
			entity.PhongTroe = null;
		}
	}
}
#pragma warning restore 1591
